# Site settings
title: from footer to header...
header-img: img/home-bg.png
email: tracypholmes@gmail.com
copyright_name: tracypholmes
description: > # this means to ignore newlines until "baseurl:"
  a blog about coding and other technological goings-on
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: tracypholmes
github_username:  tracypholmes
learn_profile: tracypholmes
email_username: tracypholmes@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: jekyll-theme-minimal